USE [LUNNA]
GO

/****** Object:  Table [dbo].[T001_USUARIOS]    Script Date: 01/09/2024 08:21:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T001_USUARIOS](
	[T001_USUARIO] [varchar](100) NOT NULL,
	[T001_SENHA] [varchar](500) NOT NULL,
	[T001_NOME] [varchar](100) NOT NULL,
	[T001_SOBRENOME] [nchar](100) NOT NULL,
	[T001_FOTO] [nchar](500) NULL,
 CONSTRAINT [PK_T001_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[T001_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


